CREATE TABLE IF NOT EXISTS account_billing_transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  initiated_by_user_id INT NULL,
  transaction_type VARCHAR(40) NOT NULL,
  product_type VARCHAR(40) NOT NULL,
  product_code VARCHAR(80) NULL,
  description VARCHAR(255) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  amount_minor INT NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'GBP',
  quantity INT NULL,
  parent_transaction_id BIGINT NULL,
  stripe_customer_id VARCHAR(64) NULL,
  stripe_checkout_session_id VARCHAR(128) NULL,
  stripe_payment_intent_id VARCHAR(128) NULL,
  stripe_charge_id VARCHAR(128) NULL,
  stripe_invoice_id VARCHAR(128) NULL,
  stripe_subscription_id VARCHAR(128) NULL,
  stripe_refund_id VARCHAR(128) NULL,
  stripe_credit_note_id VARCHAR(128) NULL,
  stripe_event_id VARCHAR(128) NULL,
  idempotency_key VARCHAR(160) NOT NULL,
  metadata JSON NULL,
  sms_ledger_processed_at DATETIME NULL,
  billing_profile_processed_at DATETIME NULL,
  reconciled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_abt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_abt_initiated_by_user FOREIGN KEY (initiated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_abt_parent FOREIGN KEY (parent_transaction_id) REFERENCES account_billing_transactions(id) ON DELETE SET NULL,
  CONSTRAINT uq_abt_stripe_event UNIQUE (stripe_event_id),
  CONSTRAINT uq_abt_idempotency_key UNIQUE (idempotency_key),
  CONSTRAINT uq_abt_refund_id UNIQUE (stripe_refund_id),
  CONSTRAINT uq_abt_checkout_session UNIQUE (stripe_checkout_session_id),
  INDEX ix_abt_user_created (user_id, created_at),
  INDEX ix_abt_payment_intent (stripe_payment_intent_id),
  INDEX ix_abt_invoice (stripe_invoice_id)
);
